language: ruby
sudo: false
cache: bundler
rvm:
- 1.9.3
services:
  - mongodb
env:
  global:
  - GOVUK_APP_DOMAIN: dev
  - DEV_DOMAIN: dev
  - CONTENTAPI_OAUTH_ID: abc123
  - CONTENTAPI_OAUTH_SECRET: abc123
  - CONTENTAPI_DEFAULT_ROLE: odi
  - CONTENTAPI_ASSET_MANAGER_BEARER_TOKEN: abc123